spring:
  application:
    name: gateway-service
  cache:
    type: redis
  data:
    redis:
      host: "localhost"
      port: 6380
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: Auth
              args:
                baseMessage: Auth Message
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
#            - Path=/api/v1/auth/register,/api/v1/auth/login
        - id: gateway
          uri: lb://gateway
          predicates:
            - Path=/api/v1/test/**
          filters:
            - name: Auth
              args:
                baseMessage: Auth Message

      discovery:
        locator:
          enabled: true

server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
  instance:
    prefer-ip-address: true

grpc:
  server:
    port: 9894
  client:
    auth-service:
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext


