spring:
  application:
    name: user-service
  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5434/kafka_user_db
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: update
  cache:
    type: redis

  data:
    redis:
      host: "localhost"
      port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${random.value}

server:
  port: 0

kafka:
  host: localhost:9092
  topics:
    user-created:
      topic: auth-service.user-created.0
      consumerGroup: ${spring.application.name}-user-created-consumer
      replicationFactor: 1
      retentionInMs: 604800000