spring:
  application:
    name: "log-service"

kafka:
  host: localhost:9092
  topics:
    user-created:
      topic: user-service.user-created.0
      consumerGroup: ${spring.application.name}-user-created-consumer
      replicationFactor: 1
      retentionInMs: 604800000
server:
  port: 8070